### PR TITLE
Euro conversion

### PR DESCRIPTION
**Pull request by Rotsides**
Added euro currency conversion from dollar and removed extra $ icon from the dollarAmount.

### CODE REVIEW

**Comment by M4rcxs** [comment]
The **EUR** and **USD** stocks are volatile. Is there an **API** available that provides **real-time** currency exchange rates? I believe using such an **API** would be more advantageous than relying on a fixed value for the **EUR** stored in a variable.

**Comment by Samathingamajig** [comment]
> The **EUR** and **USD** stocks are volatile. Is there an **API** available that provides **real-time** currency exchange rates? I believe using such an **API** would be more advantageous than relying on a fixed value for the **EUR** stored in a variable.

An API that I've used before for this conversion is https://cdn.jsdelivr.net/gh/fawazahmed0/currency-api@1/latest/currencies/usd/eur.json (replace `usd` and `eur` with other currency codes, in the form of "from" to "to").

**Comment by Samathingamajig** [comment]
If there is going to be multiple currencies, it should be a setting on the extension, not showing multiple at once, imo.

Related: #9

**Comment by davidbenjaminnovotny** [comment]
Dont know how this will work if this extension grows. Free API will only go so far.

**Comment by Samathingamajig** [comment]
> Dont know how this will work if this extension grows. Free API will only go so far.
> 
> Perhaps daily fixed static updates of the exchange rate in the extension. ( dont know if google allows this)

Cache the response and only fetch a new value once a day. If it's a concern, it's easy to spin up another daily caching layer through vercel that can save the response from that API so that it's only called once at all per day, and all instances of the extension call that vercel endpoint once a day.

**Comment by Samathingamajig** [comment]
> I'm leaning towards not implementing this for the sake of simplicity.

fortune-teller-it-could-be-fun
especially with the dogecoin possibility

**Comment by Rotsides** [comment]
> > I'm leaning towards not implementing this for the sake of simplicity.
> 
> fortune-teller-it-could-be-fun especially with the dogecoin possibility

I only added Euro because the EUR and USD are the 2 primary currencies that are most used. It was a quick implementation just to have that option too. I know it needs real time conversion but i just left it as it is for now maybe someone else wants to add to it. If you don't want to implement it no probs. I might try to implement a better version with conversion that will be updated 2-3 times per day.

**Pull request closed without merging**
